WORKING_DIR_PATH        = "D:\Data Andra\Project\ADB\ADB-Project\development"
MODELS_DIR_PATH         = WORKING_DIR_PATH + "/models"
DATAS_DIR_PATH          = WORKING_DIR_PATH + "/datas"

NN_MODEL_PATH           = MODELS_DIR_PATH + "/default/nn/nn_model.pth"
NN_LABEL_ENCODER_PATH   = MODELS_DIR_PATH + "/default/nn/label_encoder_nn.pkl"
SVM_MODEL_PATH          = MODELS_DIR_PATH + "/default/svm/svm_model.pkl"
SVM_LABEL_ENCODER_PATH  = MODELS_DIR_PATH + "/default/svm/label_encoder_svm.pkl"
RF_MODEL_PATH           = MODELS_DIR_PATH + "/default/rf/random_forest_model.pkl"
RF_LABEL_ENCODER_PATH   = MODELS_DIR_PATH + "/default/rf/label_encoder_rf.pkl"
